        const nameField =()=> cy.get('input[name=name]')
        const emailField =()=> cy.get('input[name=email]')
        const passwordField =()=> cy.get('input[name=password]')
        const tosField =()=> cy.get('input[name=tos]')
        const submitBtn =()=>  cy.get('input[name=submitBtn]')
        const UserForm = ()=> cy.get('[id="createUserForm"]')
describe('Testing Create New User Form',()=>{
    beforeEach(()=>{
        cy.visit('http://localhost:3000/')
    })

    describe('Ensure all expected input fields exist and operate correctly',()=>{
        it('tests the input fields exist',()=>{
            UserForm().should('exist')
            nameField().should('exist')
            emailField().should('exist')
            passwordField().should('exist')
            tosField().should('exist')
            submitBtn().should('exist')
        })
        it('All input fields default to empty and can accept inputs',()=>{
            nameField().should('have.value','')
            emailField().should('have.value','')
            passwordField().should('have.value','')
            tosField().should('not.be.checked')
        })
        it('input fields operate as expected individually',()=>{
            nameField()
                .type('Dawson')
                .should('have.value','Dawson')
            
            emailField()
                .type('dawsonreschke@gmail.com')
                .should('have.value','dawsonreschke@gmail.com')
            
            passwordField()
                .type('123456')
                .should('have.value','123456')
            
            tosField()
                .click()
                .should('be.checked')
            
        })
        describe('all input fields must pass a specified schema before the submit button works',()=>{
            it('if name is null error message appears',()=>{
                emailField()
                .type('dawsonreschke@gmail.com')
            
            passwordField()
                .type('123456')
            
            tosField()
                .click()
            submitBtn()
                .click()
            cy.get('body').contains('Name is a required field').should('exist')
            })
            it('if name < 2 error message appears',()=>{
                nameField()
                    .type('a')
                emailField()
                .type('dawsonreschke@gmail.com')
            
            passwordField()
                .type('123456')
            
            tosField()
                .click()
                submitBtn()
                    .click()
            cy.contains('Name must be greater than 1 character').should('exist')
            })
            it('if email is blank error message appears',()=>{
                nameField()
                    .type('Dawson')
                passwordField()
                    .type('123456')
                tosField()
                    .click()
                submitBtn()
                    .click()
                cy.contains('Email is a required field').should('exist')    
            })
            it('if password is null an error appears',()=>{
                nameField()
                    .type('Dawson')
                emailField()
                    .type('dawsonreschke@gmail.com')
                tosField()
                    .click()
                submitBtn()
                    .click()
                cy.contains('Password is a required field').should('exist')    
            })
            it('if password is less than 6 an error message appears',()=>{
                nameField()
                    .type('Dawson')
                emailField()
                    .type('dawsonreschke@gmail.com')
                passwordField()
                    .type('12345')
                tosField()
                    .click()
                submitBtn()
                    .click()
                cy.contains('Password must be at least 6 characters long').should('exist')    
            })
            it('if tos is unchecked an error message appears',()=>{
                nameField()
                    .type('Dawson')
                emailField()
                    .type('dawsonreschke@gmail.com')
                passwordField()
                    .type('123456')
                submitBtn()
                    .click()
                cy.contains('Must agree to Terms of service').should('exist')    
            })
            it('if all inputs are correct the input boxes should clear',()=>{
                nameField()
                    .type('Dawson')
                emailField()
                    .type('dawsonreschke@gmail.com')
                passwordField()
                    .type('123456')
                tosField()
                    .click()
                submitBtn()
                    .click()
                nameField().should('have.value','')
                emailField().should('have.value','')
                passwordField().should('have.value','')
                tosField().should('not.be.checked')
                })
        })
    })

})

